/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package piemenu;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bouzekel on 21/11/2016.
 * Fenêtre principale.
 */
public class Frame extends javax.swing.JFrame {
    
    double x, y;
    private PieMenu piemenu_panel;
    private int width_piemenu = 150;

    /**
     * Creates new form PieMenuFrame
     */
    public Frame() {
        this.setTitle("Ma première fenêtre Java");
        this.setSize(500, 500);
        initComponents();
        piemenu_panel = new PieMenu(getHeight(), getWidth(), x, y, width_piemenu);
        this.setContentPane(piemenu_panel);
        piemenu_panel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        if (evt.getButton() == MouseEvent.BUTTON3) {
            x = evt.getX();
            y = evt.getY();
            piemenu_panel.setXpie(x);
            piemenu_panel.setYpie(y);
            /*
            if (x-width_piemenu/2 < 0 || x+width_piemenu/2 > getWidth() || y-width_piemenu/2 < 0 || y+width_piemenu/2 > getHeight()){
                JOptionPane.showMessageDialog(null, "Il n'y a pas la place de tracer le pie menu autour du click, retentez ;)");
            }
            else {*/
                this.setVisible(true);
                piemenu_panel.setVisible(true);
                piemenu_panel.getStatemachine().cClickRight(evt.getX(), evt.getY());
            //}
        } else {
            piemenu_panel.setVisible(false);
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
